globocom/m3u8

- m3u8/model.py
- tests/test_loader.py
- tests/test_model.py
Unknown AttributeNames should be ignored, according to https://tools.ietf.org/html/draft-pantos-http-live-streaming-16#section-6.3.1.  Observed BANDWIDTH included in EXT-X-MEDIA tag from ted.com (e.g. http://hls.ted.com/talks/2297.m3u8), which is not defined, but caused an exception. Fixed that with the **extras.
Also changed semantics when an absolute path without a netloc is used in a url, so that base_url will behave like a urljoin, using base_url netloc and the given url's absolute path. Note the change to expected_ts1_abspath in test_load_should_create_object_from_uri_with_relative_segments in test_loader.py. Also impacted parsing of the same video from ted.com.
> Fixed https://github.com/globocom/m3u8/issues/42 plus other minor problems

- m3u8/parser.py
The module exceptions no longer exists.
This is based on top of 0.2.6 as the current master contains unresolved conflicts.
Andrea
> Python3 support.

- m3u8/model.py
Now all tests pass in python 3 as well.
Andrea
This is to fix
TypeError: unorderable types: NoneType() > int()
> Mote python 3 support.

- m3u8/parser.py
- tests/playlists.py
- tests/test_model.py
- tests/test_parser.py
Suggested fix for issue #58 to handle the case when key-method is NONE the key URI should not be mandatory.
> Suggested fix for #58: If key-method is None the key uri should not be mandatory

- m3u8/model.py
- m3u8/parser.py
- tests/test_model.py
Based on the discussion in #58 and in light of that the RFC stating that URI is only required if key method is not NONE I have reverted the fix. And actually other attributes MUST NOT be present if method is NONE. That part is not enforced in this commit. It may be value to keep the added test cases already merged, and why I created a new PR with the revert. It is up to you if you want to use this or just revert the old PR.
> Partial revert (maintaining the added unit tests) in the fix for #58

- m3u8/__init__.py
Added the ability to build the request for an URL specifying more
arguments such as headers.  With this option cookies, referrer and
user-agent may be passed to access the content of URLs.
Closes: #94, #82
> Add support for headers to URL opener

- m3u8/model.py
- tests/test_model.py
- tests/test_variant_m3u8.py
About problem on iOS: https://github.com/jwplayer/jwplayer/issues/1060
About this tag on draft: https://tools.ietf.org/html/draft-pantos-http-live-streaming-23
On apple dev site: https://developer.apple.com/library/content/qa/qa1801/_index.html
> Add support CLOSED-CAPTIONS for StreamInfo

- m3u8/parser.py
- tests/playlists.py
- tests/test_parser.py
m3u8 failed, when there was a comma in the title, ex
#EXTINF:295,Test 123, part 14
We can only split into max 2 parts.
> Don't fail if title has a comma in it

- requirements-dev.txt
This fixes the broken build in #119 and also corrects the issue mentioned in #118 
We might want to consider dropping support for 2.6 as the libraries we use for the tests do the same. I believe there are upgrade routes for all major platforms.
> Arrow 0.10.0 breaks 2.6 support. Pinning tests to arrow==0.9.0 fixes the issue

- m3u8/model.py
- tests/playlists.py
- tests/test_model.py
This partially addresses #121
I'm not sure about this... it seems like this could be a potentially breaking change, and I'm suspicious about the tests all passing with it. It seems to me that this (and #125) should have broken playlist serialization.
Please review.
> Add subtitles, video, and audio group-id refs to StreamInfo

- m3u8/parser.py
In the uri check method, I switched the library call "re" to the built-in "startswith".
I also used the same built-in method in the "remove_quotes" method. In the same file,
I changed the replaces of the method "string_to_lines" to "splitlines" where it has the
same effect.
> Improve readability in the parser.py file

- m3u8/__init__.py
- m3u8/model.py
- m3u8/parser.py
- tests/playlists.py
- tests/test_parser.py
Main parser function now receives a function that can be
used to parse the line content and save it into the data store object.
> Add basic support for custom tags

- requirements-dev.txt
`pytest-cov 2.6.0` has increased the version requirement for the coverage package from `>=3.7.1` to `>=4.4`, which is in conflict with the version requirement defined by the python-coveralls package for `coverage==4.0.3`.
Once `coveralls` upgrades its `coverage` dependency we can get back to a latest pytest-cov version
> Fix conflict of testing requirements

- requirements-dev.txt
- tests/test_model.py
datetime from standard library is able to perform the same operations as arrow on m3u8 codebase.
> Remove unnecessary dependency

- m3u8/model.py
- tests/test_model.py
As per https://tools.ietf.org/html/rfc8216#section-4.1, lines in a Playlist file are terminated with a new line (or a carriage return line feed).
If the manifest ends with an `#EXT-X-ENDLIST` or `#EXT-X-RENDITION-REPORT` tag (or anything other than a list of segments), this is not currently the case.
Usually this doesn't cause any issues in production, but we have found that when the line contains an attribute list ending with an integer (eg `#EXT-X-RENDITION-REPORT:URI="../1M/waitForMSN.php",LAST-MSN=273,LAST-PART=2`), iOS clients will fail to parse the integer.
> Ensure that final line is terminated as per spec

- m3u8/__init__.py
Add (and reorder to match model.py) a bunch of missing tag objects so they are available at the top level like the ones already defined.
It'd be really cool if this could go into the next release to pypi 🤞
> Make all manifest tags available at top level, not just some

- m3u8/model.py
- tests/playlists.py
- tests/test_model.py
https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-02#section-4.4.1.2 states that #EXT-X-VERSION is an integer.
Currently, attempting to set this tag as an int fails since a string is expected. This PR allows version to be set as an int.
Ideally I'd really like the parser to parse version as an integer since I think it is more intuitive, but this would be a (minor) breaking change since it is currently parsed as a string. What do you think? Particularly since a new minor version is about to be issued, it seems like an ideal time to make this change.
> Allow #EXT-X-VERSION to be set as int as well as str

- m3u8/__init__.py
Not every server has SSL enabled with valid
certificates. This commit adds an option to disable
by passing verify_ssl as False when loading a playlist.
> Option to disable SSL verification

- m3u8/model.py
- tests/test_model.py
Dumping of LAST-PART was disabled if the value was falsy. This is incorrect since 0 is a valid value for LAST-PART.
I only noticed this now we are actually implementing this stuff 😄
Be good if this could make its way into the version that must be about to drop on pypi?
> Ensure correct dumping of rendition report when LAST-PART is 0

- m3u8/parser.py
- tests/test_model.py
- tests/test_parser.py
As discussed in #161, `#EXT-X-VERSION` is an `int` in the specification. I think it is more intuitive for version to be parsed as an int rather than a string.
Note that this is a (small) breaking change since an `int` rather than a string will be returned - see the change to `test_should_parse_VERSION` in test_parser.py.
I don't feel super-strongly about this, but it seems more spec-compliant and code using this library looks more sensible (in my opinion)
> Parse EXT-X-VERSION as an int as per spec

- m3u8/parser.py
`DeprecationWarning: invalid escape sequence \d` was being thrown due to non-raw string being used for regex.
My error, apologies.
> Fix invalid escape sequence in regex

- m3u8/model.py
Stores them in self._extra_params as a dictionary in the Key objects.
This is to help fix the following error when using key rotation in HLS:
```
File "/Users/anon/bin/m3u8util.py", line 730, in cli_download
playlist = m3u8.loads(rdata.text)
File "/Users/anon/.virtualenvs/fd/lib/python3.8/site-packages/m3u8/__init__.py", line 42, in loads
return M3U8(content, custom_tags_parser=custom_tags_parser)
File "/Users/anon/.virtualenvs/fd/lib/python3.8/site-packages/m3u8/model.py", line 155, in __init__
self._initialize_attributes()
File "/Users/anon/.virtualenvs/fd/lib/python3.8/site-packages/m3u8/model.py", line 160, in _initialize_attributes
self.keys = [ Key(base_uri=self.base_uri, **params) if params else None
File "/Users/anon/.virtualenvs/fd/lib/python3.8/site-packages/m3u8/model.py", line …
```
> Added ability for extra parameters to be passed to Key class

- README.rst
- m3u8/model.py
- m3u8/parser.py
- m3u8/protocol.py
- tests/playlists.py
- tests/test_model.py
- tests/test_parser.py
As defined https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-05#section-4.4.2.7 and in the draft LLHLS extensions.
Crafted during these long COVID nights ...
> EXT-X-GAP support

- m3u8/model.py
- tests/test_model.py
Fairly sure occasional test failures with `test_daterange_simple` were caused by non-explicit ordering of automatically parsed and dumped client attributes from a DATERANGE tag.
The problem occurs when there are _multiple_ client attributes because the parsing and dumping order was not explicitly defined but the test expected a certain order that was not guaranteed.
Fix is to explicitly sort client attributes (alphabetically by name) at dumping time. This may mean that they are not in the order of input, but all other attributes are output in a fixed order so this is never true anyway.
> Order DATERANGE x-<client-attr>s predictably

- m3u8/model.py
- tests/playlists.py
- tests/test_model.py
Duration containing 0.000011 should not be converted to 1.1e-0 when dumping the playlist.
Fixes #210
> EXTINF tag must not violate floating point spec

- README.rst
- m3u8/__init__.py
- m3u8/httpclient.py
With this change, users can now use `requests` or another HTTP client.
Besides that, users can now use proxies by passing `proxies` to the default client constructor.
> Allow users to use custom HTTP clients

- m3u8/model.py
- m3u8/parser.py
- tests/playlists.py
- tests/test_parser.py
- tests/test_variant_m3u8.py
This is a very quick pass at adding support for VIDEO-RANGE from files with the following structure:
```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-STREAM-INF:BANDWIDTH=6352852,AVERAGE-BANDWIDTH=6180023,VIDEO-RANGE=SDR,CODECS="avc1.4d4028,mp4a.40.2",RESOLUTION=1920x1080,FRAME-RATE=24.000,AUDIO="program_audio_0"
MXF-1080p.m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="program_audio_0",LANGUAGE="eng",NAME="Alternate Audio",AUTOSELECT=YES,DEFAULT=YES,URI="/v1/media/cf/MXF-aud.m3u8"
#EXT-X-STREAM-INF:BANDWIDTH=4236849,AVERAGE-BANDWIDTH=4167098,VIDEO-RANGE=SDR,CODECS="avc1.4d401f,mp4a.40.2",RESOLUTION=1280x720,FRAME-RATE=24.000,AUDIO="program_audio_0"
MXF-720p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=10618822,AVERAGE-BANDWIDTH=10255013,VIDEO-RANGE=PQ,CODECS="dvh1.05.03,mp4a.40.2",RESOLUTION=19 …
```
> Support VIDEO-RANGE in StreamInfo

- m3u8/model.py
- m3u8/parser.py
- tests/playlists.py
- tests/test_parser.py
- tests/test_variant_m3u8.py
VIDEO-RANGE is also useful for IFramePlaylists.
https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-07#section-4.4.6.2
VIDEO-RANGE
The value is an enumerated-string; valid strings are SDR, HLG and
PQ.
The value MUST be SDR if the video in the Variant Stream is
encoded using one of the following reference opto-electronic
transfer characteristic functions specified by the
TransferCharacteristics code point: [CICP] 1, 6, 13, 14, 15.  Note
that different TransferCharacteristics code points can use the
same transfer function.
The value MUST be HLG if the video in the Variant Stream is
encoded using a reference opto-electronic transfer characteristic
function specified by the TransferCharacteristics code point 18,
or consists of such video mixed with video qualifying as SDR (see
above).
The …
> Adds VIDEO-RANGE to IFramePlaylist

- .github/workflows/main.yml
CI move to Github Actions because Travis-CI.org  is shutting down soon.
>  Please be aware travis-ci.org will be shutting down by end of May 2021. Please consider migrating to travis-ci.com.
> Github actions CI suggestion

- tests/test_model.py
Use the `tmpdir` fixture like the other tests.
Related: NixOS/nixpkgs#146667
> Fix hardcoded `/tmp` directory in test

- m3u8/model.py
- m3u8/parser.py
There are small typos in:
- m3u8/model.py
- m3u8/parser.py
Fixes:
- Should read `precede` rather than `preceed`.
- Should read `separately` rather than `seperately`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- README.rst
- m3u8/model.py
- m3u8/parser.py
- m3u8/protocol.py
- tests/playlists.py
- tests/test_parser.py
What have been already implementing:
- Changed the priority of calling the  custom_tags_parser
- Added the ability to control whether should 'main' parser go to the next line or not after custom_tags_parser has finished
- The Segment class has been extended for storing custom values
```
#EXTM3U
#EXTINF: -1 timeshift="0" catchup-days="1" catchup-type="flussonic-ts" tvg-id="ethno-channel"  group-title="Ukraine" tvg-logo="http://iptv.domain/icon/7331.png",Етно HD
#EXTVLCOPT:video-filter=invert:croppadd{croptop=50,cropbottom=50}
#EXTGRP:MaybeUkraine
#EXTVLCOPT:param2=value2
http://str00.iptv.domain/7331/mpegts?token=longtokenhere
```
**Example of new custom_tags_parser function, which allow parsing the playlist above**
```
def parse_iptv_attributes(line, lineno, data, state):
if …
```
> Extend custom_tags_parser functionality

- m3u8/model.py
- m3u8/parser.py
- tests/playlists.py
- tests/test_parser.py
Adds support for `STABLE-VARIANT-ID` and `STABLE-RENDITION-ID` tags as per https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis-11.
https://github.com/globocom/m3u8/pull/265 had merge conflicts and implementation issues (variant IDs not added to iframes, rendition IDs not added), requester seems inactive
> Add support for stable variant/rendition IDs

- m3u8/model.py
- tests/test_model.py
Fixes #291
This PR updates `M3U8.dump` such that it uses `exist_ok=True` when creating directories with `os.makedirs`.
The intended behavior now obtains:
* if the directory already exists, it will be used.
* if not, it will be created.
* if there was some error in creating it, the associated exception will be raised.
> Use os.makedirs with exist_ok=True

- README.rst
Currently all the Supported tags mentioned in the `README.rst` file does not have links provided to them, therefore now I have added the links to them however I was not able to find the proper links to
* #EXT-X-CUE-OUT
* #EXT-X-CUE-OUT-CONT
* #EXT-X-CUE-IN
* #EXT-X-CUE-SPAN
* #EXT-OATCLS-SCTE35
that's why I have kept them as it is in the same format as mentioned above and for the tags I found the link I mentioned them as the rest of the tags with link as
*  "EXT-X-ALLOW-CACHE"_ (i.e. in place of this " this ` ticks)
> Updated ReadMe file

- .github/workflows/main.yml
- m3u8/model.py
- tests/test_model.py
Re: [Issue 308](https://github.com/globocom/m3u8/issues/308), this PR adds a `media_sequence` attribute to `Segment` objects.
From RFC 8216:
```
Each segment in a Media Playlist has a unique integer Media Sequence
Number.  The Media Sequence Number of the first segment in the Media
Playlist is either 0 or declared in the Playlist ([Section 4.4.3.2](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.3.2)).
The Media Sequence Number of every other segment is equal to the
Media Sequence Number of the segment that precedes it plus one.
```
It's useful to have access to the Media Sequence number on the `Segment` object because this value can be used for the initialization vector (section 5.2). It's also useful for tracking changes between requests of live playlists.
> Add Segment.media_Sequence

- m3u8/model.py
- tests/test_model.py
- tests/test_parser.py
* Code based on [PEP 8 Style Guide](https://www.python.org/dev/peps/pep-0008/)
> Comparisons to singletons like None should always be done with is or is not, never the equality operators.
> Comparisons to singletons - PEP8 style guide

- m3u8/model.py
I did some profiling of this module with `cProfile` and found that the most expensive part of the `dumps` function is the `number_to_string`, which uses the `decimal` module.
This PR changes removes few calls to `number_to_string` where it's possible:
* `EXT-X-DISCONTINUITY-SEQUENCE` is necessarily an integer, per RFC 8216
* `LAST-MSN`
* `SKIPPED-SEGMENTS`
> Avoid using decimal.Decimal for integer values

- m3u8/__init__.py
- m3u8/httpclient.py
- m3u8/mixins.py
- m3u8/parser.py
- tests/playlists/relative-playlist.m3u8
- tests/test_loader.py
- tests/test_model.py
This PR updates how the `absolute_uri` method for objects that use the `BasePathMixin`.
I think the changes related to issue #245 and PR #263 introduced some unusual and surprising behavior. The issue related to handling relative URLs that start with `//`, like `//segment.ts`.
Joining URLs is covered by [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986.html), which specifically describes the `//` case. From [section 5.4.1](https://www.rfc-editor.org/rfc/rfc3986.html#section-5.4.1):
Python's built-in `urllib.parse.urljoin` produces the expected result, but `m3u8.parse.urljoin` does not:
```python
>>> from urllib.parse import urljoin as python_urljoin
>>> from m3u8.parser import urljoin as m3u8_urljoin
>>> m3u8_urljoin('http://a/b/c/d;p?q', '//g')
'http://a//g'
>>> …
```
> Re-work URL joining to follow RFC 3986

- m3u8/parser.py
- tests/playlists.py
- tests/test_parser.py
Re: issue #326, this PR updates the parser code such that a URL is not required after the `EXTINF` tag.
> Issue 326: allow tags after EXTINF

- m3u8/parser.py
- requirements.txt
- setup.py
> Use built-in ISO 8601 parse for Python 3.11 and later

- m3u8/model.py
- tests/test_model.py
Currently, `Segment` accepts `timespec` but it's not available at the top of the chain, so this PR adds the ability to pass it all the way down
(I'd also like to make `microseconds` the default, but didn't want to change behavior while adding the feature, so that could be an exercise for a future date)
> Pass timespec all the way down in dumps

- m3u8/parser.py
This PR doesn't add any functionality, so I'll understand if you'd rather not take it. But I often found myself scrolling back and forth between sections of `parser.py` to look to see how a certain tag parser was called, and decided to try to make everything consistent.
The `parse` function now loops over the lines, checks for known tags, and always calls a parse function with these arguments:
* line
* lineno
* data
* state
* strict
The parse functions accept all of the arguments as keywords, and if they don't need them, they don't act on them. All state / data updating logic is handled inside the parse functions.
I find that this makes the `parse` loop easier to think about, and it makes the process of adding support for new tags easier.
> Refactor parser.py to use consistent arguments

- m3u8/model.py
- m3u8/parser.py
- tests/test_model.py
- tests/test_parser.py
See #376.
Would break people who are doing `data["segments"][0]["bitrate"] == "1674"` (which is the intention), because we wish bitrate to be `int`.
Would also break people who are doing `obj.segments[0].bitrate = "9876"` because `dumps` explicitly requires `int` now, which I think is fine but could be changed to be more lenient.
> Parse Bitrate value as integer not string

- tests/test_loader.py
Fix a file path error in the loader test, introduced at the pull request number 388, as mentioned in the comment: 
https://github.com/globocom/m3u8/pull/388#discussion_r1919428851
.
> Fix a file path error in the loader test.
